export const allCharges = {
  air: {
    freight: [
      'ATA Freight',
      'AWB Fee',
      'Accessorial Charges',
      'Airline Handling',
      'All Inclusive',
      'COVID-19 Surcharge',
      'Cargo Data Declaration Fee',
      'Cargo Insurance',
      'Customs Clearance',
      'Destination Delivery Charge',
      'Detention',
      'Documentation charges - Destination',
      'Emergency Rate Surcharge',
      'Export Entry',
      'Export Freight',
      'Export Service',
      'Hazardous Surcharge',
      'Import Freight',
      'Importer Security Filing',
      'On-Carriage',
      'Overweight Surcharge',
      'Peak Season Surcharge',
      'Road Haulage',
      'Special Equipment Surcharge',
      'Terminal Handling Charge - Destination',
      'Terminal Handling Service - Destination',
      'Terminal Handling Service - Origin'
    ],
    origin: [
      'All Inclusive',
      'Automated Manifest System',
      'Chassis Usage Surcharge/Chassis Fee',
      'Customs Clearance',
      'Documentation Changes - Origin',
      'Fuel Surcharge',
      'Packing Charges',
      'Road Haulage - Pickup Charge',
      'Terminal Handling Charge - Origin'
    ],
    destination: [
      'All Inclusive',
      'Custom Clearance',
      'Destination Delivery Charge',
      'Destination Terminal Handling Charge',
      'Documentation Charges',
      'Fuel Surcharge',
      'Handling Fee',
      'Release Fee',
      'Transit Accompanying Document',
      'Unpacking Charges'
    ],
    additional: ['Customs Brokerage', 'Insurance']
  },
  sea: {
    freight: [
      'Accessorial Charges',
      'Aden War Risk Surcharge',
      'All Inclusive',
      'BL Fee',
      'Bunker Adjustment Factor',
      'Bunker Charge',
      'COVID-19 Surcharge',
      'Cargo Data Declaration Fee',
      'Cargo Insurance',
      'Currency Adjustment Factor',
      'Customs Clearance',
      'Destination Delivery Charge',
      'Detention',
      'Documentation charges - Destination',
      'Emergency Bunker Surcharge',
      'Emergency Rate Restoration',
      'Environment Fee Destination',
      'Equipment Imbalance Surcharge',
      'Equipment Repositioning Surcharge',
      'Export Entry',
      'Export Service',
      'General Rate Increase',
      'Gulf of Aden Surcharge',
      'Hazardous Surcharge',
      'Importer Security Filing',
      'International Security Port Surcharge',
      'Low Sulphur Surcharge',
      'Ocean Freight Cost',
      'On-Carriage',
      'Over Weight Surcharge',
      'Peak Season Surcharge',
      'Piracy Surcharge',
      'Port Dues',
      'Road Haulage',
      'Special Equipment Surcharge',
      'Suez Canal Surcharge',
      'Terminal Handling Charge - Destination',
      'Terminal Handling Service - Destination',
      'Terminal Handling Service - Origin'
    ],
    origin: [
      'All Inclusive',
      'Automated Manifest System',
      'Chassis Usage Surcharge/Chassis Fee',
      'Customs Clearance',
      'Documentation Charges - Origin',
      'Fuel Surcharge',
      'Packing Charges',
      'Road Haulage - Pickup Charge',
      'Terminal Handling Charge - Origin',
      'Wharfage'
    ],
    destination: [
      'All Inclusive',
      'Chassis Utilization Surcharge',
      'Container Yard Receiving Charge',
      'Customs Clearance',
      'Demurrage/Detention',
      'Destination Delivery Charge',
      'Destination Terminal Handling Charge',
      'Documentation charges',
      'Fuel Surcharge',
      'Handling Fee',
      'Release Fee',
      'Transit Accompanying Document',
      'Unpacking charges',
      'Wharfage'
    ],
    additional: ['Customs Brokerage', 'Insurance']
  }
}
